# .docker/nginx/conf.d/ehub.conf

server {
    listen 80;
    listen [::]:80;
    server_name _;

    set $ehub_client http://ehub-client:80;
    set $ehub_server http://ehub-server:7777;
    set $ehub_minio http://minio:9000;

    location /nginx-health {
        access_log off;
        return 200 "healthy\n";
    }

    location /api/ {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $ehub_server;
    }

    location /ehub/ {
        include /etc/nginx/snippets/minio-proxy-params.conf;
        proxy_pass $ehub_minio;
    }

    location /ehubd/ {
        include /etc/nginx/snippets/minio-proxy-params.conf;
        proxy_pass $ehub_minio;
    }

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $ehub_client;
    }
}
