# .docker/nginx/conf.d/ehub.conf

upstream ehub_client {
    server ehub-client:80;
}

upstream ehub_server {
    server ehub-server:7777;
}

upstream ehub_minio {
    server minio:9000;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /nginx-health {
        access_log off;
        return 200 "healthy\n";
    }

    location /api/ {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass http://ehub_server;
    }

    location /ehub/ {
        include /etc/nginx/snippets/minio-proxy-params.conf;
        proxy_pass http://ehub_minio;
    }

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass http://ehub_client;
    }
}
