import { useTranslation } from "@/context/TranslationContext";

// Calm palette: gom mọi status về 4 tone token (success / warning / danger / neutral).
// Caller vẫn truyền value như cũ; chỉ thay đổi CSS (không đổi logic/nhãn).
const TONE_STYLES = {
  success: "bg-success-bg text-success-text",
  warning: "bg-warning-bg text-warning-text",
  danger: "bg-danger-bg text-danger-text",
  neutral: "bg-neutral-bg text-neutral-text",
};

const SUCCESS = new Set([
  "active", "ongoing", "completed", "open", "graduated", "public", "business",
  "accepted", "sent", "used", "graded", "published", "presented", "on_track",
  "has_feedback", "enough", "excellent", "launched", "revenue", "successful",
  "done", "high_potential", "follow_up", "converted_to_assignment", "alumni",
  "alumni_founder", "social_impact", "investor", "investor_interest", "investor_fund",
  "investor_meeting", "grant", "funding", "funding_connection", "winner",
]);

const WARNING = new Set([
  "pending", "on_hold", "pending_mentor", "pending_grading", "resubmitted",
  "processing", "sending", "rescheduled", "shortage", "missing_feedback",
  "watchlist", "high", "no_session", "no_progress_update", "needs_more_info",
  "applied", "contacted", "shortlisted", "invited", "proposed",
]);

const DANGER = new Set([
  "locked", "rejected", "deleted", "late", "no_show", "revoked", "failed",
  "cancelled", "expired", "declined", "critical", "overloaded", "at_risk",
  "urgent", "no_mentor", "follow_up_overdue", "dead", "absent", "withdrawn",
  "needs_attention", "no_partner_connection",
]);

function toneOf(key) {
  if (SUCCESS.has(key)) return "success";
  if (WARNING.has(key)) return "warning";
  if (DANGER.has(key)) return "danger";
  if (/^\d{3}$/.test(key)) {
    const code = parseInt(key, 10);
    if (code >= 200 && code < 300) return "success";
    if (code >= 400 && code < 600) return code < 500 ? "warning" : "danger";
  }
  return "neutral";
}

const labelMap = {
  active: "Active",
  inactive: "Inactive",
  locked: "Locked",
  local: "Local",
  google: "Google",
  upcoming: "Upcoming",
  ongoing: "Ongoing",
  completed: "Completed",
  draft: "Draft",
  open: "Open",
  closed: "Closed",
  archived: "Archived",
  candidate: "Candidate",
  incubating: "Incubating",
  on_hold: "On hold",
  graduated: "Graduated",
  pending: "Pending",
  proposed: "Proposed",
  pending_mentor: "Pending mentor",
  rejected: "Rejected",
  private: "Private",
  internal: "Internal",
  public: "Public",
  business: "Business",
  technical: "Technical",
  primary: "Primary",
  supporting: "Supporting",
  internal_lecturer: "Internal lecturer",
  external_expert: "External expert",
  deleted: "Deleted",
  not_submitted: "Not submitted",
  submitted: "Submitted",
  confirmed: "Confirmed",
  resubmitted: "Resubmitted",
  pending_grading: "Pending grading",
  graded: "Graded",
  late: "Late",
  checkpoint: "Checkpoint",
  assignment: "Assignment",
  final: "Final",
  class_invite: "Class invite",
  group_invite: "Group invite",
  email_event: "Email event",
  queued: "Queued",
  sending: "Sending",
  sent: "Sent",
  used: "Used",
  accepted: "Accepted",
  declined: "Declined",
  expired: "Expired",
  revoked: "Revoked",
  processing: "Processing",
  failed: "Failed",
  cancelled: "Cancelled",
  scheduled: "Scheduled",
  no_show: "No show",
  rescheduled: "Rescheduled",
  online: "Online",
  offline: "Offline",
  hybrid: "Hybrid",
  rule_based: "Rule based",
  ai: "AI",
  generated: "Generated",
  converted_to_assignment: "Converted",
  shortlisted: "Shortlisted",
  ignored: "Ignored",
  in_progress: "In progress",
  low: "Low",
  medium: "Medium",
  normal: "Normal",
  high: "High",
  excellent: "Excellent",
  overloaded: "Overloaded",
  enough: "Enough",
  shortage: "Shortage",
  critical: "Critical",
  no_mentor: "No mentor",
  no_session: "No session",
  on_track: "On track",
  needs_attention: "Needs attention",
  has_feedback: "Has feedback",
  missing_feedback: "Missing feedback",
  urgent: "Urgent",
  idea: "Idea",
  prototype: "Prototype",
  mvp: "MVP",
  beta: "Beta",
  launched: "Launched",
  revenue: "Revenue",
  company: "Company",
  market_validation: "Market validation",
  company_registered: "Company registered",
  module3_selection: "Module 3 selection",
  manual_nomination: "Manual nomination",
  showcase: "Showcase",
  alumni: "Alumni",
  other: "Other",
  evaluation_result: "Evaluation result",
  mentor_recommendation: "Mentor recommendation",
  ai_suggestion: "AI suggestion",
  needs_more_info: "Needs more info",
  founder: "Founder",
  co_founder: "Co-founder",
  member: "Member",
  advisor: "Advisor",
  alumni_founder: "Alumni founder",
  pitch_deck: "Pitch deck",
  business_plan: "Business plan",
  demo_video: "Demo video",
  logo: "Logo",
  certificate: "Certificate",
  report: "Report",
  product: "Product",
  team: "Team",
  funding: "Funding",
  award: "Award",
  partnership: "Partnership",
  legal: "Legal",
  customer: "Customer",
  market: "Market",
  mentor: "Mentor",
  funding_connection: "Funding connection",
  legal_advice: "Legal advice",
  marketing: "Marketing",
  mentor_session: "Mentor session",
  workshop: "Workshop",
  partner_intro: "Partner intro",
  investor_intro: "Investor intro",
  review_meeting: "Review meeting",
  demo_day: "Demo day",
  pitching_day: "Pitching day",
  networking: "Networking",
  competition: "Competition",
  published: "Published",
  invited: "Invited",
  presented: "Presented",
  absent: "Absent",
  withdrawn: "Withdrawn",
  lecturer: "Lecturer",
  partner: "Partner",
  investor: "Investor",
  guest: "Guest",
  none: "None",
  follow_up: "Follow up",
  winner: "Winner",
  runner_up: "Runner up",
  best_pitch: "Best pitch",
  best_technology: "Best technology",
  best_business_model: "Best business model",
  social_impact: "Social impact",
  image: "Image",
  video: "Video",
  document: "Document",
  link: "Link",
  incubator: "Incubator",
  accelerator: "Accelerator",
  investor_fund: "Investor fund",
  angel_investor: "Angel investor",
  university: "University",
  government: "Government",
  ngo: "NGO",
  community: "Community",
  introduction: "Introduction",
  pilot: "Pilot",
  investor_interest: "Investor interest",
  incubation_program: "Incubation program",
  contacted: "Contacted",
  successful: "Successful",
  grant: "Grant",
  pilot_program: "Pilot program",
  investor_meeting: "Investor meeting",
  applied: "Applied",
  no_progress_update: "No progress update",
  no_partner_connection: "No partner connection",
  follow_up_overdue: "Follow-up overdue",
  done: "Done",
  dead: "Dead",
  manual: "Manual",
  weighted_sum: "Weighted sum",
  high_potential: "High potential",
  watchlist: "Watchlist",
  at_risk: "At risk",
  true: "System",
  false: "Custom",
};

export default function StatusBadge({ value }) {
  const { t } = useTranslation();
  const key = String(value);
  const label = t(`status.${key}`);
  const displayLabel = label === `status.${key}` ? (labelMap[key] || key) : label;

  return (
    <span className={`inline-flex items-center rounded-control px-2 py-0.5 text-xs font-medium ${TONE_STYLES[toneOf(key)]}`}>
      {displayLabel}
    </span>
  );
}
