import { useTranslation } from "@/context/TranslationContext";

const statusMap = {
  active: "bg-emerald-50 text-emerald-700 border-emerald-100",
  inactive: "bg-slate-50 text-slate-600 border-slate-200",
  locked: "bg-red-50 text-red-600 border-red-100",
  local: "bg-blue-50 text-blue-700 border-blue-100",
  google: "bg-amber-50 text-amber-700 border-amber-100",
  upcoming: "bg-sky-50 text-sky-700 border-sky-100",
  ongoing: "bg-emerald-50 text-emerald-700 border-emerald-100",
  completed: "bg-violet-50 text-violet-700 border-violet-100",
  draft: "bg-slate-50 text-slate-600 border-slate-200",
  open: "bg-emerald-50 text-emerald-700 border-emerald-100",
  closed: "bg-slate-50 text-slate-600 border-slate-200",
  archived: "bg-zinc-50 text-zinc-600 border-zinc-200",
  pending: "bg-amber-50 text-amber-700 border-amber-100",
  proposed: "bg-blue-50 text-blue-700 border-blue-100",
  pending_mentor: "bg-amber-50 text-amber-700 border-amber-100",
  rejected: "bg-red-50 text-red-700 border-red-100",
  private: "bg-slate-50 text-slate-600 border-slate-200",
  internal: "bg-blue-50 text-blue-700 border-blue-100",
  public: "bg-emerald-50 text-emerald-700 border-emerald-100",
  business: "bg-emerald-50 text-emerald-700 border-emerald-100",
  technical: "bg-sky-50 text-sky-700 border-sky-100",
  primary: "bg-indigo-50 text-indigo-700 border-indigo-100",
  supporting: "bg-slate-50 text-slate-600 border-slate-200",
  internal_lecturer: "bg-indigo-50 text-indigo-700 border-indigo-100",
  external_expert: "bg-violet-50 text-violet-700 border-violet-100",
  deleted: "bg-red-50 text-red-600 border-red-100",
  not_submitted: "bg-slate-50 text-slate-600 border-slate-200",
  submitted: "bg-blue-50 text-blue-700 border-blue-100",
  confirmed: "bg-indigo-50 text-indigo-700 border-indigo-100",
  resubmitted: "bg-amber-50 text-amber-700 border-amber-100",
  pending_grading: "bg-amber-50 text-amber-700 border-amber-100",
  graded: "bg-emerald-50 text-emerald-700 border-emerald-100",
  late: "bg-red-50 text-red-700 border-red-100",
  checkpoint: "bg-indigo-50 text-indigo-700 border-indigo-100",
  assignment: "bg-sky-50 text-sky-700 border-sky-100",
  final: "bg-violet-50 text-violet-700 border-violet-100",
  class_invite: "bg-blue-50 text-blue-700 border-blue-100",
  group_invite: "bg-indigo-50 text-indigo-700 border-indigo-100",
  email_event: "bg-cyan-50 text-cyan-700 border-cyan-100",
  queued: "bg-blue-50 text-blue-700 border-blue-100",
  sending: "bg-amber-50 text-amber-700 border-amber-100",
  sent: "bg-emerald-50 text-emerald-700 border-emerald-100",
  used: "bg-emerald-50 text-emerald-700 border-emerald-100",
  accepted: "bg-emerald-50 text-emerald-700 border-emerald-100",
  declined: "bg-red-50 text-red-700 border-red-100",
  expired: "bg-slate-50 text-slate-600 border-slate-200",
  revoked: "bg-red-50 text-red-700 border-red-100",
  processing: "bg-amber-50 text-amber-700 border-amber-100",
  failed: "bg-red-50 text-red-700 border-red-100",
  cancelled: "bg-slate-50 text-slate-600 border-slate-200",
  scheduled: "bg-blue-50 text-blue-700 border-blue-100",
  no_show: "bg-red-50 text-red-700 border-red-100",
  rescheduled: "bg-amber-50 text-amber-700 border-amber-100",
  online: "bg-sky-50 text-sky-700 border-sky-100",
  offline: "bg-emerald-50 text-emerald-700 border-emerald-100",
  hybrid: "bg-violet-50 text-violet-700 border-violet-100",
  rule_based: "bg-slate-50 text-slate-600 border-slate-200",
  ai: "bg-indigo-50 text-indigo-700 border-indigo-100",
  generated: "bg-teal-50 text-teal-700 border-teal-100",
  converted_to_assignment: "bg-emerald-50 text-emerald-700 border-emerald-100",
  shortlisted: "bg-blue-50 text-blue-700 border-blue-100",
  ignored: "bg-slate-50 text-slate-600 border-slate-200",
  in_progress: "bg-blue-50 text-blue-700 border-blue-100",
  low: "bg-slate-50 text-slate-600 border-slate-200",
  medium: "bg-blue-50 text-blue-700 border-blue-100",
  normal: "bg-blue-50 text-blue-700 border-blue-100",
  high: "bg-amber-50 text-amber-700 border-amber-100",
  excellent: "bg-emerald-50 text-emerald-700 border-emerald-100",
  overloaded: "bg-red-50 text-red-700 border-red-100",
  enough: "bg-emerald-50 text-emerald-700 border-emerald-100",
  shortage: "bg-amber-50 text-amber-700 border-amber-100",
  critical: "bg-red-50 text-red-700 border-red-100",
  no_mentor: "bg-red-50 text-red-700 border-red-100",
  no_session: "bg-amber-50 text-amber-700 border-amber-100",
  on_track: "bg-emerald-50 text-emerald-700 border-emerald-100",
  needs_attention: "bg-orange-50 text-orange-700 border-orange-100",
  has_feedback: "bg-emerald-50 text-emerald-700 border-emerald-100",
  missing_feedback: "bg-amber-50 text-amber-700 border-amber-100",
  urgent: "bg-red-50 text-red-700 border-red-100",
  done: "bg-emerald-50 text-emerald-700 border-emerald-100",
  dead: "bg-red-50 text-red-700 border-red-100",
  manual: "bg-slate-50 text-slate-600 border-slate-200",
  weighted_sum: "bg-blue-50 text-blue-700 border-blue-100",
  high_potential: "bg-emerald-50 text-emerald-700 border-emerald-100",
  watchlist: "bg-amber-50 text-amber-700 border-amber-100",
  at_risk: "bg-red-50 text-red-700 border-red-100",
  true: "bg-indigo-50 text-indigo-700 border-indigo-100",
  false: "bg-gray-50 text-gray-600 border-gray-100",
};

const labelMap = {
  active: "Active",
  inactive: "Inactive",
  locked: "Locked",
  local: "Local",
  google: "Google",
  upcoming: "Upcoming",
  ongoing: "Ongoing",
  completed: "Completed",
  draft: "Draft",
  open: "Open",
  closed: "Closed",
  archived: "Archived",
  pending: "Pending",
  proposed: "Proposed",
  pending_mentor: "Pending mentor",
  rejected: "Rejected",
  private: "Private",
  internal: "Internal",
  public: "Public",
  business: "Business",
  technical: "Technical",
  primary: "Primary",
  supporting: "Supporting",
  internal_lecturer: "Internal lecturer",
  external_expert: "External expert",
  deleted: "Deleted",
  not_submitted: "Not submitted",
  submitted: "Submitted",
  confirmed: "Confirmed",
  resubmitted: "Resubmitted",
  pending_grading: "Pending grading",
  graded: "Graded",
  late: "Late",
  checkpoint: "Checkpoint",
  assignment: "Assignment",
  final: "Final",
  class_invite: "Class invite",
  group_invite: "Group invite",
  email_event: "Email event",
  queued: "Queued",
  sending: "Sending",
  sent: "Sent",
  used: "Used",
  accepted: "Accepted",
  declined: "Declined",
  expired: "Expired",
  revoked: "Revoked",
  processing: "Processing",
  failed: "Failed",
  cancelled: "Cancelled",
  scheduled: "Scheduled",
  no_show: "No show",
  rescheduled: "Rescheduled",
  online: "Online",
  offline: "Offline",
  hybrid: "Hybrid",
  rule_based: "Rule based",
  ai: "AI",
  generated: "Generated",
  converted_to_assignment: "Converted",
  shortlisted: "Shortlisted",
  ignored: "Ignored",
  in_progress: "In progress",
  low: "Low",
  medium: "Medium",
  normal: "Normal",
  high: "High",
  excellent: "Excellent",
  overloaded: "Overloaded",
  enough: "Enough",
  shortage: "Shortage",
  critical: "Critical",
  no_mentor: "No mentor",
  no_session: "No session",
  on_track: "On track",
  needs_attention: "Needs attention",
  has_feedback: "Has feedback",
  missing_feedback: "Missing feedback",
  urgent: "Urgent",
  done: "Done",
  dead: "Dead",
  manual: "Manual",
  weighted_sum: "Weighted sum",
  high_potential: "High potential",
  watchlist: "Watchlist",
  at_risk: "At risk",
  true: "System",
  false: "Custom",
};

export default function StatusBadge({ value }) {
  const { t } = useTranslation();
  const key = String(value);
  const label = t(`status.${key}`);
  const displayLabel = label === `status.${key}` ? (labelMap[key] || key) : label;

  let customStyle = statusMap[key];
  if (!customStyle && /^\d{3}$/.test(key)) {
    const code = parseInt(key, 10);
    if (code >= 200 && code < 300) {
      customStyle = "bg-emerald-50 text-emerald-700 border-emerald-100";
    } else if (code >= 300 && code < 400) {
      customStyle = "bg-blue-50 text-blue-700 border-blue-100";
    } else if (code >= 400 && code < 500) {
      customStyle = "bg-amber-50 text-amber-700 border-amber-100";
    } else if (code >= 500 && code < 600) {
      customStyle = "bg-red-50 text-red-700 border-red-100";
    }
  }

  return (
    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold ${customStyle || "bg-gray-50 text-gray-600 border-gray-100"}`}>
      {displayLabel}
    </span>
  );
}
