import instance from "../instance";
import { compactQuery } from "../adminAcademic/utils";

const IncubationApi = {
  listStartups: (query = {}) => instance.get("/admin/incubation/startups", { params: compactQuery(query) }),
  createStartup: (body) => instance.post("/admin/incubation/startups", body),
  getStartup: (id) => instance.get(`/admin/incubation/startups/${id}`),
  updateStartup: (id, body) => instance.put(`/admin/incubation/startups/${id}`, body),
  deleteStartup: (id) => instance.delete(`/admin/incubation/startups/${id}`),
  createStartupFromGroup: (groupId, body) => instance.post(`/admin/incubation/startups/from-group/${groupId}`, body),

  listSelectionReviews: (query = {}) => instance.get("/admin/incubation/selection-reviews", { params: compactQuery(query) }),
  createSelectionReview: (body) => instance.post("/admin/incubation/selection-reviews", body),
  reviewSelection: (id, body) => instance.patch(`/admin/incubation/selection-reviews/${id}/review`, body),

  listStages: (query = {}) => instance.get("/admin/incubation/pipeline/stages", { params: compactQuery(query) }),
  createStage: (body) => instance.post("/admin/incubation/pipeline/stages", body),
  updateStage: (id, body) => instance.put(`/admin/incubation/pipeline/stages/${id}`, body),
  moveStage: (id, body) => instance.patch(`/admin/incubation/startups/${id}/stage`, body),
  getHistory: (id) => instance.get(`/admin/incubation/startups/${id}/history`),

  listDocuments: (id) => instance.get(`/admin/incubation/startups/${id}/documents`),
  initiateDocumentUpload: (id, body) => instance.post(`/admin/incubation/startups/${id}/documents/initiate-upload`, body),
  confirmDocumentUpload: (id, uploadToken) => instance.post(`/admin/incubation/startups/${id}/documents`, { upload_token: uploadToken }),
  deleteDocument: (id, documentId) => instance.delete(`/admin/incubation/startups/${id}/documents/${documentId}`),

  listMilestones: (id) => instance.get(`/admin/incubation/startups/${id}/milestones`),
  createMilestone: (id, body) => instance.post(`/admin/incubation/startups/${id}/milestones`, body),
  updateMilestone: (id, milestoneId, body) => instance.put(`/admin/incubation/startups/${id}/milestones/${milestoneId}`, body),
  deleteMilestone: (id, milestoneId) => instance.delete(`/admin/incubation/startups/${id}/milestones/${milestoneId}`),

  listProgress: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/progress`, { params: compactQuery(query) }),
  createProgress: (id, body) => instance.post(`/admin/incubation/startups/${id}/progress`, body),
  updateProgress: (id, progressId, body) => instance.put(`/admin/incubation/startups/${id}/progress/${progressId}`, body),
  deleteProgress: (id, progressId) => instance.delete(`/admin/incubation/startups/${id}/progress/${progressId}`),
  listMetrics: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/metrics`, { params: compactQuery(query) }),
  createMetrics: (id, body) => instance.post(`/admin/incubation/startups/${id}/metrics`, body),
  listSupportNeeds: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/support-needs`, { params: compactQuery(query) }),
  createSupportNeed: (id, body) => instance.post(`/admin/incubation/startups/${id}/support-needs`, body),
  updateSupportNeedStatus: (supportNeedId, body) => instance.patch(`/admin/incubation/support-needs/${supportNeedId}/status`, body),
  listSupportActivities: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/support-activities`, { params: compactQuery(query) }),
  createSupportActivity: (id, body) => instance.post(`/admin/incubation/startups/${id}/support-activities`, body),
  listAwards: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/awards`, { params: compactQuery(query) }),
  createAward: (id, body) => instance.post(`/admin/incubation/startups/${id}/awards`, body),

  listEvents: (query = {}) => instance.get("/admin/ecosystem/events", { params: compactQuery(query) }),
  createEvent: (body) => instance.post("/admin/ecosystem/events", body),
  getEvent: (id) => instance.get(`/admin/ecosystem/events/${id}`),
  updateEvent: (id, body) => instance.put(`/admin/ecosystem/events/${id}`, body),
  updateEventStatus: (id, body) => instance.patch(`/admin/ecosystem/events/${id}/status`, body),
  deleteEvent: (id) => instance.delete(`/admin/ecosystem/events/${id}`),
  listEventStartups: (id, query = {}) => instance.get(`/admin/ecosystem/events/${id}/startups`, { params: compactQuery(query) }),
  addEventStartup: (id, body) => instance.post(`/admin/ecosystem/events/${id}/startups`, body),
  deleteEventStartup: (id, startupId) => instance.delete(`/admin/ecosystem/events/${id}/startups/${startupId}`),
  listEventJudges: (id, query = {}) => instance.get(`/admin/ecosystem/events/${id}/judges`, { params: compactQuery(query) }),
  addEventJudge: (id, body) => instance.post(`/admin/ecosystem/events/${id}/judges`, body),
  deleteEventJudge: (id, judgeId) => instance.delete(`/admin/ecosystem/events/${id}/judges/${judgeId}`),
  listEventFeedbacks: (id, query = {}) => instance.get(`/admin/ecosystem/events/${id}/feedbacks`, { params: compactQuery(query) }),
  createEventFeedback: (id, body) => instance.post(`/admin/ecosystem/events/${id}/feedbacks`, body),
  listEventMedia: (id, query = {}) => instance.get(`/admin/ecosystem/events/${id}/media`, { params: compactQuery(query) }),
  createEventMedia: (id, body) => instance.post(`/admin/ecosystem/events/${id}/media`, body),

  listAlumni: (query = {}) => instance.get("/admin/ecosystem/alumni", { params: compactQuery(query) }),
  createAlumni: (body) => instance.post("/admin/ecosystem/alumni", body),
  getAlumni: (id) => instance.get(`/admin/ecosystem/alumni/${id}`),
  updateAlumni: (id, body) => instance.put(`/admin/ecosystem/alumni/${id}`, body),
  deleteAlumni: (id) => instance.delete(`/admin/ecosystem/alumni/${id}`),

  listPartners: (query = {}) => instance.get("/admin/ecosystem/partners", { params: compactQuery(query) }),
  createPartner: (body) => instance.post("/admin/ecosystem/partners", body),
  getPartner: (id) => instance.get(`/admin/ecosystem/partners/${id}`),
  updatePartner: (id, body) => instance.put(`/admin/ecosystem/partners/${id}`, body),
  deletePartner: (id) => instance.delete(`/admin/ecosystem/partners/${id}`),

  listStartupPartners: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/partners`, { params: compactQuery(query) }),
  createStartupPartner: (id, body) => instance.post(`/admin/incubation/startups/${id}/partners`, body),
  updatePartnerConnectionStatus: (id, body) => instance.patch(`/admin/startup-partner-connections/${id}/status`, body),

  listOpportunities: (query = {}) => instance.get("/admin/ecosystem/opportunities", { params: compactQuery(query) }),
  createOpportunity: (body) => instance.post("/admin/ecosystem/opportunities", body),
  getOpportunity: (id) => instance.get(`/admin/ecosystem/opportunities/${id}`),
  updateOpportunity: (id, body) => instance.put(`/admin/ecosystem/opportunities/${id}`, body),
  updateOpportunityStatus: (id, body) => instance.patch(`/admin/ecosystem/opportunities/${id}/status`, body),
  listStartupOpportunities: (id, query = {}) => instance.get(`/admin/incubation/startups/${id}/opportunities`, { params: compactQuery(query) }),
  applyOpportunity: (startupId, opportunityId, body) => instance.post(`/admin/incubation/startups/${startupId}/opportunities/${opportunityId}/apply`, body),
  updateOpportunityApplicationStatus: (id, body) => instance.patch(`/admin/startup-opportunity-applications/${id}/status`, body),

  analyticsOverview: (query = {}) => instance.get("/admin/incubation/analytics/overview", { params: compactQuery(query) }),
  analyticsPipeline: (query = {}) => instance.get("/admin/incubation/analytics/pipeline", { params: compactQuery(query) }),
  analyticsProgress: (query = {}) => instance.get("/admin/incubation/analytics/progress", { params: compactQuery(query) }),
  analyticsEvents: (query = {}) => instance.get("/admin/incubation/analytics/events", { params: compactQuery(query) }),
  analyticsAlumniPartners: (query = {}) => instance.get("/admin/incubation/analytics/alumni-partners", { params: compactQuery(query) }),
  analyticsEcosystemHealth: (query = {}) => instance.get("/admin/incubation/analytics/ecosystem-health", { params: compactQuery(query) }),
  startupReports: (query = {}) => instance.get("/admin/incubation/reports/startups", { params: compactQuery(query) }),
  startupReport: (id) => instance.get(`/admin/incubation/reports/startups/${id}`),

  lecturerNominations: (query = {}) => instance.get("/lecturer/incubation/nominations", { params: compactQuery(query) }),
  lecturerNominate: (groupId, body) => instance.post(`/lecturer/groups/${groupId}/nominate-startup`, body),

  myStartups: (query = {}) => instance.get("/student/startup-profiles", { params: compactQuery(query) }),
  myStartup: (startupId) => instance.get(`/student/startup-profiles/${startupId}`),
  myStartupById: (startupId) => instance.get(`/student/startups/${startupId}`),
  updateMyStartup: (startupId, body) => instance.put(`/student/startup-profiles/${startupId}`, body),
  myStartupProgress: (startupId, query = {}) => instance.get(`/student/startups/${startupId}/progress`, { params: compactQuery(query) }),
  createMyStartupProgress: (startupId, body) => instance.post(`/student/startups/${startupId}/progress`, body),
  myStartupSupportNeeds: (startupId, query = {}) => instance.get(`/student/startups/${startupId}/support-needs`, { params: compactQuery(query) }),
  createMyStartupSupportNeed: (startupId, body) => instance.post(`/student/startups/${startupId}/support-needs`, body),
  studentOpportunities: (query = {}) => instance.get("/student/ecosystem/opportunities", { params: compactQuery(query) }),
  myStartupOpportunities: (startupId, query = {}) => instance.get(`/student/startups/${startupId}/opportunities`, { params: compactQuery(query) }),
  applyMyStartupOpportunity: (startupId, opportunityId, body) => instance.post(`/student/startups/${startupId}/opportunities/${opportunityId}/apply`, body),

  mentorStartup: (startupId) => instance.get(`/mentor/startups/${startupId}`),
  mentorStartupProgress: (startupId, query = {}) => instance.get(`/mentor/startups/${startupId}/progress`, { params: compactQuery(query) }),
};

export default IncubationApi;
