-- =============================================
-- INIT DATA DE18 COHORT — FA2025 / SP2026 / SU2026
-- Generated by ehub-server/scripts/database/gen_de18_cohort_seed.py
-- Source: DE18 (Copy).json
-- =============================================
-- FA2025: DE18FA01 (EXE101, 20 SV) + DE18FA02 (EXE201, 20 SV), lec1
--         MSSV: 40 codes available in DE180212–DE180290 (gaps skipped)
-- SP2026: DE18SP01 (EXE101, DE180001–040), lec1, 8 teams
-- SU2026: DE18SU01 (EXE201, same 40 SV + same team roster), lec2
-- Note: DE180034 is BL in source JSON; seeded as students.status=active
-- Prerequisite: users lec1 / lec2 already exist (init_schema.js)
-- Do not run together with init_data_lec1.sql (MSSV overlap)
-- =============================================
SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';

SET @lec1_id = (SELECT id FROM users WHERE username = 'lec1' LIMIT 1);
SET @lec2_id = (SELECT id FROM users WHERE username = 'lec2' LIMIT 1);

SET @subject1_id = (SELECT id FROM subjects WHERE subject_code = 'EXE101' LIMIT 1);
SET @subject2_id = (SELECT id FROM subjects WHERE subject_code = 'EXE201' LIMIT 1);
SET @subject1_id = IFNULL(@subject1_id, 1);
SET @subject2_id = IFNULL(@subject2_id, 2);

INSERT INTO students (student_code, full_name, email, major, status, created_at, updated_at) VALUES
('DE180212', 'Trần Đình Duy Phương', 'PhuongTDDDE180212@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180213', 'Lê Thu Tiền', 'TienLTDE180213@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180214', 'Đinh A Sang Đông', 'DongDASDE180214@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180215', 'PHAN THANH NGUYÊN', 'NGUYENPTDE180215@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180216', 'Nguyễn Phước Hoài Nhật', 'NhatNPHDE180216@fpt.edu.vn', 'IA', 'active', NOW(), NOW()),
('DE180217', 'Phan Thanh Nghĩa', 'NghiaPTDE180217@fpt.edu.vn', 'AI', 'active', NOW(), NOW()),
('DE180218', 'VƯƠNG MAI NGÂN', 'NGANVMDE180218@fpt.edu.vn', 'IA', 'active', NOW(), NOW()),
('DE180219', 'Lê Đức Kiệt', 'KietLDDE180219@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180220', 'Trần Nhật Huy Hoàng', 'HoangTNHDE180220@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180221', 'Trương Đình Nhật', 'NhatTDDE180221@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180222', 'La Huy Bách', 'BachLHDE180222@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180223', 'Đoàn Thị Kim Ngân', 'NganDTKDE180223@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180224', 'Trần Phạm Minh Sa', 'SaTPMDE180224@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180225', 'Thái Ngọc Linh', 'LinhTNDE180225@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180226', 'PHAN VĂN KHIÊM', 'KHIEMPVDE180226@fpt.edu.vn', 'AI', 'active', NOW(), NOW()),
('DE180227', 'Nguyễn Ngọc Phong', 'PhongNNDE180227@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180228', 'Nguyễn Lê Quân', 'QuanNLDE180228@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180229', 'Phan Thành Chung', 'ChungPTDE180229@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180230', 'Ngô Huy Long', 'LongNHDE180230@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180231', 'Nguyễn Phúc Sang', 'SangNPDE180231@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180232', 'Nguyễn Hoài Nam', 'NamNHDE180232@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180271', 'Đặng Quang Minh', 'MinhDQDE180271@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180272', 'Lê Quang Ánh', 'AnhLQDE180272@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180273', 'Nguyễn Huy Long', 'LongNHDE180273@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180274', 'Nguyễn Phạm Thanh Bình', 'BinhNPTDE180274@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180275', 'Võ Trần Đăng Khoa', 'KhoaVTDDE180275@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180276', 'Lê Thị Thảo Nhi', 'NhiLTTDE180276@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180277', 'Lương Văn Tuấn Kiệt', 'KietLVTDE180277@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180278', 'Trần Nguyên Hân', 'HanTNDE180278@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180279', 'Nguyễn Tuấn Minh', 'MinhNTDE180279@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180280', 'Nguyễn Lê Đăng Thành', 'ThanhNLDDE180280@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180281', 'Trương Nhật Huy', 'HuyTNDE180281@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180282', 'Lê Tuấn Kiệt', 'KietLTDE180282@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180283', 'Lê Phước Diệu My', 'MyLPDDE180283@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180284', 'Nguyễn Bảo Châu', 'ChauNBDE180284@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180285', 'Lê Tấn Đại', 'DaiLTDE180285@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180286', 'Trần Đình Quý', 'QuyTDDE180286@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180287', 'Nguyễn Anh Việt', 'VietNADE180287@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180288', 'Nguyễn Huy Vũ', 'VuNHDE180288@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180289', 'Trương Nhật Thạch', 'ThachTNDE180289@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180001', 'Benjamin Chinonso Onuoma', 'BenjaminDE180001@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180002', 'Temitope Mayowa Ajayi', 'AJAYIDE180002@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180003', 'Nguyễn Thị Minh Thư', 'ThuNTMDE180003@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180004', 'Nguyễn Tiến Dũng', 'DungNTDE180004@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180005', 'Lê Đình Nhật Nam', 'NamLDNDE180005@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180006', 'Lê Thế Cường', 'CuongLTDE180006@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180007', 'Nguyễn Thị Phương Uyên', 'UyenNTPDE180007@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180008', 'Nguyễn Đình Quang Vinh', 'VinhNDQDE180008@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180009', 'Nguyễn Bá Hoàng', 'HoangNBDE180009@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180010', 'Nguyễn Tuấn Thành', 'ThanhNTDE180010@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180011', 'Chu Minh Giang', 'GiangCMDE180011@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180012', 'Nguyễn Thị Minh Hải', 'HaiNTMDE180012@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180013', 'Nguyễn Đình Quang', 'QuangNDDE180013@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180014', 'Võ Nguyên Vũ', 'VuVNDE180014@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180015', 'Lê Công Cường', 'CuongLCDE180015@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180016', 'Hoàng Anh Tiến', 'TienHADE180016@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180017', 'Dương Trí Toàn', 'ToanDTDE180017@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180018', 'Lê Phúc Tiến', 'TienLPDE180018@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180019', 'Lê Ngọc Thiên Phú', 'PhuLNTDE180019@fpt.edu.vn', 'IA', 'active', NOW(), NOW()),
('DE180020', 'Trần Kim Thắng', 'ThangTKDE180020@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180021', 'Đặng Đình Hùng', 'HungDDDE180021@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180022', 'Trần Bình Vương', 'VuongTBDE180022@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180023', 'Nguyễn Hữu Nam Khánh', 'KhanhNHNDE180023@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180024', 'Phan Hồng Bảo Ngọc', 'NgocPHBDE180024@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180025', 'Phạm Minh Quân', 'QuanPMDE180025@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180026', 'Tống Thị Như Quỳnh', 'QuynhTTNDE180026@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180027', 'Trần Mạnh Dũng', 'DungTMDE180027@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180028', 'Nguyễn Văn Nam', 'NamNVDE180028@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180029', 'Lê Thanh Tùng', 'TungLTDE180029@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180030', 'Nguyễn Khắc Anh', 'AnhNKDE180030@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180031', 'Nguyễn Thị Cẩm Tú', 'TuNTCDE180031@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180032', 'Bùi Quang Linh', 'LinhBQDE180032@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180033', 'Lương Văn Giang', 'GiangLVDE180033@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180034', 'Phạm Lê Tiến Anh', 'AnhPLTDE180034@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180035', 'Nguyễn Thu Trang', 'TrangNTDE180035@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180036', 'Đào Thị Kiều Trang', 'TrangDTKDE180036@fpt.edu.vn', 'GD', 'active', NOW(), NOW()),
('DE180037', 'Hoàng Gia Bảo', 'BaoHGDE180037@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180038', 'Hoàng Vũ Hưng', 'HungHVDE180038@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180039', 'Nguyễn Hoàng Dương', 'DuongNHDE180039@fpt.edu.vn', 'SE', 'active', NOW(), NOW()),
('DE180040', 'Lê Đức Đạt', 'DatLDDE180040@fpt.edu.vn', 'SE', 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE full_name = VALUES(full_name), email = VALUES(email), major = VALUES(major), status = 'active';

-- -------------------------------------------
-- FA2025 (completed) — two classes, different students
-- -------------------------------------------
INSERT IGNORE INTO semesters (semester_code, semester_name, year, start_date, end_date, status, created_at, updated_at)
VALUES ('FA2025', 'Fall 2025', 2025, '2025-09-01', '2025-12-20', 'completed', NOW(), NOW());
SET @sem_fa25_id = (SELECT id FROM semesters WHERE semester_code = 'FA2025' LIMIT 1);

INSERT INTO classes (subject_id, semester_id, class_code, class_name, lecturer_id, max_students, min_group_members, max_group_members, status, created_by, created_at, updated_at)
VALUES (@subject1_id, @sem_fa25_id, 'DE18FA01', 'DE18FA01', @lec1_id, 20, 5, 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE lecturer_id = @lec1_id, status = 'active';
SET @class_fa01_id = (SELECT id FROM classes WHERE class_code = 'DE18FA01' AND semester_id = @sem_fa25_id LIMIT 1);

INSERT IGNORE INTO class_students (class_id, student_id, status, enrolled_at)
SELECT @class_fa01_id, id, 'completed', NOW() FROM students WHERE student_code IN ('DE180212', 'DE180213', 'DE180214', 'DE180215', 'DE180216', 'DE180217', 'DE180218', 'DE180219', 'DE180220', 'DE180221', 'DE180222', 'DE180223', 'DE180224', 'DE180225', 'DE180226', 'DE180227', 'DE180228', 'DE180229', 'DE180230', 'DE180231');

INSERT INTO `groups` (class_id, group_code, group_name, description, max_members, status, created_by, created_at, updated_at)
VALUES
  (@class_fa01_id, 'G01', 'Team Alpha', 'Team G01 — DE18FA01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa01_id, 'G02', 'Team Beta', 'Team G02 — DE18FA01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa01_id, 'G03', 'Team Gamma', 'Team G03 — DE18FA01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa01_id, 'G04', 'Team Delta', 'Team G04 — DE18FA01', 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE group_name = VALUES(group_name), status = 'active';
SET @fa01_g01 = (SELECT id FROM `groups` WHERE class_id = @class_fa01_id AND group_code = 'G01' LIMIT 1);
SET @fa01_g02 = (SELECT id FROM `groups` WHERE class_id = @class_fa01_id AND group_code = 'G02' LIMIT 1);
SET @fa01_g03 = (SELECT id FROM `groups` WHERE class_id = @class_fa01_id AND group_code = 'G03' LIMIT 1);
SET @fa01_g04 = (SELECT id FROM `groups` WHERE class_id = @class_fa01_id AND group_code = 'G04' LIMIT 1);

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g01, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180212';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g01, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180213', 'DE180214', 'DE180215', 'DE180216');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g02, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180217';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g02, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180218', 'DE180219', 'DE180220', 'DE180221');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g03, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180222';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g03, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180223', 'DE180224', 'DE180225', 'DE180226');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g04, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180227';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa01_g04, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180228', 'DE180229', 'DE180230', 'DE180231');

INSERT INTO classes (subject_id, semester_id, class_code, class_name, lecturer_id, max_students, min_group_members, max_group_members, status, created_by, created_at, updated_at)
VALUES (@subject2_id, @sem_fa25_id, 'DE18FA02', 'DE18FA02', @lec1_id, 20, 5, 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE lecturer_id = @lec1_id, status = 'active';
SET @class_fa02_id = (SELECT id FROM classes WHERE class_code = 'DE18FA02' AND semester_id = @sem_fa25_id LIMIT 1);

INSERT IGNORE INTO class_students (class_id, student_id, status, enrolled_at)
SELECT @class_fa02_id, id, 'completed', NOW() FROM students WHERE student_code IN ('DE180232', 'DE180271', 'DE180272', 'DE180273', 'DE180274', 'DE180275', 'DE180276', 'DE180277', 'DE180278', 'DE180279', 'DE180280', 'DE180281', 'DE180282', 'DE180283', 'DE180284', 'DE180285', 'DE180286', 'DE180287', 'DE180288', 'DE180289');

INSERT INTO `groups` (class_id, group_code, group_name, description, max_members, status, created_by, created_at, updated_at)
VALUES
  (@class_fa02_id, 'G01', 'Team Alpha', 'Team G01 — DE18FA02', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa02_id, 'G02', 'Team Beta', 'Team G02 — DE18FA02', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa02_id, 'G03', 'Team Gamma', 'Team G03 — DE18FA02', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_fa02_id, 'G04', 'Team Delta', 'Team G04 — DE18FA02', 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE group_name = VALUES(group_name), status = 'active';
SET @fa02_g01 = (SELECT id FROM `groups` WHERE class_id = @class_fa02_id AND group_code = 'G01' LIMIT 1);
SET @fa02_g02 = (SELECT id FROM `groups` WHERE class_id = @class_fa02_id AND group_code = 'G02' LIMIT 1);
SET @fa02_g03 = (SELECT id FROM `groups` WHERE class_id = @class_fa02_id AND group_code = 'G03' LIMIT 1);
SET @fa02_g04 = (SELECT id FROM `groups` WHERE class_id = @class_fa02_id AND group_code = 'G04' LIMIT 1);

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g01, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180232';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g01, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180271', 'DE180272', 'DE180273', 'DE180274');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g02, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180275';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g02, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180276', 'DE180277', 'DE180278', 'DE180279');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g03, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180280';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g03, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180281', 'DE180282', 'DE180283', 'DE180284');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g04, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180285';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @fa02_g04, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180286', 'DE180287', 'DE180288', 'DE180289');

-- -------------------------------------------
-- SP2026 (completed) — DE18SP01 EXE101, 40 SV, lec1
-- -------------------------------------------
INSERT IGNORE INTO semesters (semester_code, semester_name, year, start_date, end_date, status, created_at, updated_at)
VALUES ('SP2026', 'Spring 2026', 2026, '2026-01-15', '2026-05-20', 'completed', NOW(), NOW());
SET @sem_sp26_id = (SELECT id FROM semesters WHERE semester_code = 'SP2026' LIMIT 1);

INSERT INTO classes (subject_id, semester_id, class_code, class_name, lecturer_id, max_students, min_group_members, max_group_members, status, created_by, created_at, updated_at)
VALUES (@subject1_id, @sem_sp26_id, 'DE18SP01', 'DE18SP01', @lec1_id, 40, 5, 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE lecturer_id = @lec1_id, status = 'active';
SET @class_sp01_id = (SELECT id FROM classes WHERE class_code = 'DE18SP01' AND semester_id = @sem_sp26_id LIMIT 1);

INSERT IGNORE INTO class_students (class_id, student_id, status, enrolled_at)
SELECT @class_sp01_id, id, 'completed', NOW() FROM students WHERE student_code IN ('DE180001', 'DE180002', 'DE180003', 'DE180004', 'DE180005', 'DE180006', 'DE180007', 'DE180008', 'DE180009', 'DE180010', 'DE180011', 'DE180012', 'DE180013', 'DE180014', 'DE180015', 'DE180016', 'DE180017', 'DE180018', 'DE180019', 'DE180020', 'DE180021', 'DE180022', 'DE180023', 'DE180024', 'DE180025', 'DE180026', 'DE180027', 'DE180028', 'DE180029', 'DE180030', 'DE180031', 'DE180032', 'DE180033', 'DE180034', 'DE180035', 'DE180036', 'DE180037', 'DE180038', 'DE180039', 'DE180040');

INSERT INTO `groups` (class_id, group_code, group_name, description, max_members, status, created_by, created_at, updated_at)
VALUES
  (@class_sp01_id, 'G01', 'Team Alpha', 'Team G01 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G02', 'Team Beta', 'Team G02 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G03', 'Team Gamma', 'Team G03 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G04', 'Team Delta', 'Team G04 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G05', 'Team Epsilon', 'Team G05 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G06', 'Team Zeta', 'Team G06 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G07', 'Team Eta', 'Team G07 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW()),
  (@class_sp01_id, 'G08', 'Team Theta', 'Team G08 — DE18SP01', 5, 'active', @lec1_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE group_name = VALUES(group_name), status = 'active';

SET @sp01_g01 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G01' LIMIT 1);
SET @sp01_g02 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G02' LIMIT 1);
SET @sp01_g03 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G03' LIMIT 1);
SET @sp01_g04 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G04' LIMIT 1);
SET @sp01_g05 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G05' LIMIT 1);
SET @sp01_g06 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G06' LIMIT 1);
SET @sp01_g07 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G07' LIMIT 1);
SET @sp01_g08 = (SELECT id FROM `groups` WHERE class_id = @class_sp01_id AND group_code = 'G08' LIMIT 1);

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g01, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180001';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g01, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180002', 'DE180003', 'DE180004', 'DE180005');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g02, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180006';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g02, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180007', 'DE180008', 'DE180009', 'DE180010');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g03, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180011';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g03, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180012', 'DE180013', 'DE180014', 'DE180015');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g04, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180016';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g04, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180017', 'DE180018', 'DE180019', 'DE180020');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g05, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180021';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g05, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180022', 'DE180023', 'DE180024', 'DE180025');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g06, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180026';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g06, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180027', 'DE180028', 'DE180029', 'DE180030');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g07, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180031';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g07, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180032', 'DE180033', 'DE180034', 'DE180035');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g08, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180036';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @sp01_g08, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180037', 'DE180038', 'DE180039', 'DE180040');

-- -------------------------------------------
-- SU2026 (ongoing) — DE18SU01 EXE201, same 40 SV + same teams, lec2
-- -------------------------------------------
INSERT IGNORE INTO semesters (semester_code, semester_name, year, start_date, end_date, status, created_at, updated_at)
VALUES ('SU2026', 'Summer 2026', 2026, '2026-05-25', '2026-08-31', 'ongoing', NOW(), NOW());
SET @sem_su26_id = (SELECT id FROM semesters WHERE semester_code = 'SU2026' LIMIT 1);

INSERT INTO classes (subject_id, semester_id, class_code, class_name, lecturer_id, max_students, min_group_members, max_group_members, status, created_by, created_at, updated_at)
VALUES (@subject2_id, @sem_su26_id, 'DE18SU01', 'DE18SU01', @lec2_id, 40, 5, 5, 'active', @lec2_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE lecturer_id = @lec2_id, status = 'active';
SET @class_su01_id = (SELECT id FROM classes WHERE class_code = 'DE18SU01' AND semester_id = @sem_su26_id LIMIT 1);

INSERT IGNORE INTO class_students (class_id, student_id, status, enrolled_at)
SELECT @class_su01_id, id, 'enrolled', NOW() FROM students WHERE student_code IN ('DE180001', 'DE180002', 'DE180003', 'DE180004', 'DE180005', 'DE180006', 'DE180007', 'DE180008', 'DE180009', 'DE180010', 'DE180011', 'DE180012', 'DE180013', 'DE180014', 'DE180015', 'DE180016', 'DE180017', 'DE180018', 'DE180019', 'DE180020', 'DE180021', 'DE180022', 'DE180023', 'DE180024', 'DE180025', 'DE180026', 'DE180027', 'DE180028', 'DE180029', 'DE180030', 'DE180031', 'DE180032', 'DE180033', 'DE180034', 'DE180035', 'DE180036', 'DE180037', 'DE180038', 'DE180039', 'DE180040');

INSERT INTO `groups` (class_id, group_code, group_name, description, max_members, status, created_by, created_at, updated_at)
VALUES
  (@class_su01_id, 'G01', 'Team Alpha', 'Team G01 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G02', 'Team Beta', 'Team G02 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G03', 'Team Gamma', 'Team G03 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G04', 'Team Delta', 'Team G04 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G05', 'Team Epsilon', 'Team G05 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G06', 'Team Zeta', 'Team G06 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G07', 'Team Eta', 'Team G07 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW()),
  (@class_su01_id, 'G08', 'Team Theta', 'Team G08 — DE18SU01', 5, 'active', @lec2_id, NOW(), NOW())
ON DUPLICATE KEY UPDATE group_name = VALUES(group_name), status = 'active';

SET @su01_g01 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G01' LIMIT 1);
SET @su01_g02 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G02' LIMIT 1);
SET @su01_g03 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G03' LIMIT 1);
SET @su01_g04 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G04' LIMIT 1);
SET @su01_g05 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G05' LIMIT 1);
SET @su01_g06 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G06' LIMIT 1);
SET @su01_g07 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G07' LIMIT 1);
SET @su01_g08 = (SELECT id FROM `groups` WHERE class_id = @class_su01_id AND group_code = 'G08' LIMIT 1);

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g01, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180001';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g01, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180002', 'DE180003', 'DE180004', 'DE180005');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g02, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180006';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g02, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180007', 'DE180008', 'DE180009', 'DE180010');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g03, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180011';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g03, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180012', 'DE180013', 'DE180014', 'DE180015');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g04, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180016';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g04, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180017', 'DE180018', 'DE180019', 'DE180020');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g05, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180021';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g05, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180022', 'DE180023', 'DE180024', 'DE180025');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g06, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180026';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g06, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180027', 'DE180028', 'DE180029', 'DE180030');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g07, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180031';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g07, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180032', 'DE180033', 'DE180034', 'DE180035');

INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g08, id, 'leader', 'active', NOW() FROM students WHERE student_code = 'DE180036';
INSERT IGNORE INTO group_members (group_id, student_id, role, status, joined_at)
SELECT @su01_g08, id, 'member', 'active', NOW() FROM students WHERE student_code IN ('DE180037', 'DE180038', 'DE180039', 'DE180040');

-- -------------------------------------------
-- Sanity checks (optional)
-- -------------------------------------------
SELECT 'lecturers' AS check_name, @lec1_id AS lec1_id, @lec2_id AS lec2_id;
SELECT c.class_code, sem.semester_code, sub.subject_code, u.username AS lecturer, COUNT(DISTINCT cs.student_id) AS enrolled, COUNT(DISTINCT g.id) AS teams FROM classes c JOIN semesters sem ON sem.id = c.semester_id JOIN subjects sub ON sub.id = c.subject_id LEFT JOIN users u ON u.id = c.lecturer_id LEFT JOIN class_students cs ON cs.class_id = c.id LEFT JOIN `groups` g ON g.class_id = c.id AND g.deleted_at IS NULL WHERE c.class_code IN ('DE18FA01','DE18FA02','DE18SP01','DE18SU01') GROUP BY c.id, c.class_code, sem.semester_code, sub.subject_code, u.username ORDER BY sem.semester_code, c.class_code;

