import { useMemo } from "react";
import { useTranslation } from "@/context/TranslationContext";

/** Shared admin table column and copy helpers. */
export function getAdminColumns(t) {
  return {
    title: t("admin.columns.title"),
    description: t("admin.columns.description"),
    status: t("admin.fields.status"),
    class: t("admin.columns.class"),
    subject: t("admin.columns.subject"),
    semester: t("admin.columns.semester"),
    type: t("filterLabels.type"),
    order: t("admin.columns.order"),
    deadline: t("filterLabels.deadline"),
    openAt: t("admin.columns.openAt"),
    max: t("admin.columns.max"),
    weight: t("admin.columns.weight"),
    files: t("admin.columns.files"),
    submitted: t("admin.columns.submitted"),
    needGrade: t("admin.columns.needGrade"),
    group: t("admin.fields.group"),
    topic: t("admin.columns.topic"),
    category: t("admin.columns.category"),
    mentor: t("admin.columns.mentor"),
    members: t("admin.fields.members"),
    lastUpdated: t("admin.columns.lastUpdated"),
    createdBy: t("admin.columns.createdBy"),
    created: t("common.created"),
    updated: t("common.updated"),
    totalScore: t("admin.columns.totalScore"),
    rubric: t("admin.columns.rubric"),
    criterion: t("admin.columns.criterion"),
    feedback: t("admin.columns.feedback"),
    required: t("admin.columns.required"),
    optional: t("admin.columns.optional"),
    attempts: t("admin.columns.attempts"),
    lastError: t("admin.columns.lastError"),
    expiresRetry: t("admin.columns.expiresRetry"),
    action: t("admin.fields.action"),
    table: t("admin.columns.table"),
    record: t("admin.columns.record"),
    student: t("admin.columns.student"),
    enrolledAt: t("admin.columns.enrolledAt"),
    noGroup: t("admin.columns.noGroup"),
    noTopic: t("admin.columns.noTopic"),
    projectTopic: t("admin.columns.projectTopic"),
    zaloLink: t("admin.columns.zaloLink"),
    mentorName: t("admin.columns.mentorName"),
    mentorDept: t("admin.columns.mentorDept"),
    topicDescription: t("admin.columns.topicDescription"),
    gradedBy: t("admin.columns.gradedBy"),
    gradedAt: t("admin.columns.gradedAt"),
    item: t("admin.columns.item"),
    source: t("filterLabels.source"),
    grader: t("filterLabels.grader"),
    bindings: t("admin.columns.bindings"),
    evaluations: t("admin.columns.evaluations"),
    version: t("admin.columns.version"),
    session: t("admin.columns.session"),
    evaluator: t("admin.columns.evaluator"),
    evaluated: t("admin.columns.evaluated"),
    pending: t("admin.columns.pending"),
    percentage: t("admin.columns.percentage"),
    file: t("admin.columns.file"),
    targetTable: t("admin.columns.targetTable"),
    targetClass: t("admin.columns.targetClass"),
    total: t("admin.columns.total"),
    success: t("admin.columns.success"),
    started: t("admin.columns.started"),
    completed: t("admin.columns.completed"),
    score: t("admin.fields.score"),
  };
}

export function useAdminColumns() {
  const { t } = useTranslation();
  return useMemo(() => getAdminColumns(t), [t]);
}
